add doc for cloudwatch container insights
aws-otel/aws-otel.github.io pull request #103
Opened 2021-04-21 05:35 UTC by pxaws

Add public doc for supporting CloudWatch Container Insights in EKS. This doc is a part of the next release for AWS OpenTelemetry Collector.

2021-04-22 20:25 UTC, mxiamxia commented on src/docs/getting-started/cloudwatch-container-insights.mdx
> +From this data, CloudWatch creates aggregated metrics at the cluster, node, pod, task, and service level as CloudWatch metrics.
```suggestion
Amazon CloudWatch can creates the aggregated CloudWatch metrics for the cluster, node, pod, task, and service level from the received EMF data.
```

2021-04-22 20:25 UTC, mxiamxia commented on src/docs/getting-started/cloudwatch-container-insights.mdx
> +Exsting CloudWatch Container Insights relies on ECS Agent and CloudWatch Agent to collect infrastructure metrics for many resources such as
```suggestion
CloudWatch Container Insights has been supported by ECS Agent and CloudWatch Agent to collect infrastructure metrics for many resources such as
```

2021-04-22 20:25 UTC, mxiamxia commented on src/docs/getting-started/cloudwatch-container-insights.mdx
> +To use AWS OTel Collector to collect infrastructure metrics for your cluster, we need to [make sure all the prerequisites are satisfied.](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitorin
```suggestion
To use AWS OTel Collector to collect infrastructure metrics for your service cluster, we need to make sure [all the prerequisites](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-prerequisites.html) are satisfied.
```

2021-04-22 20:25 UTC, mxiamxia commented on src/docs/getting-started/cloudwatch-container-insights.mdx
> +## Configurations to support CloudWatch Container Insights for EKS
```suggestion
## Configurations to support CloudWatch Container Insights for EKS EC2
```

2021-04-22 20:50 UTC, pxaws commented on src/docs/getting-started/cloudwatch-container-insights.mdx
> +    In this tutorial, we will walk through how to enable CloudWatch Container Insights with AWS OTel Collector for an EKS cluster.
Will change accordingly.

2021-04-22 20:51 UTC, pxaws commented on src/docs/getting-started/cloudwatch-container-insights.mdx
> +From this data, CloudWatch creates aggregated metrics at the cluster, node, pod, task, and service level as CloudWatch metrics.
Will change accordingly.

2021-04-22 20:51 UTC, pxaws commented on src/docs/getting-started/cloudwatch-container-insights.mdx
> +Exsting CloudWatch Container Insights relies on ECS Agent and CloudWatch Agent to collect infrastructure metrics for many resources such as
Will change accordingly.

2021-04-22 20:53 UTC, pxaws commented on src/docs/getting-started/cloudwatch-container-insights.mdx
> +## Configurations to support CloudWatch Container Insights for EKS
Will change accordingly.

2021-04-22 20:53 UTC, pxaws commented on src/docs/getting-started/cloudwatch-container-insights.mdx
> +To use AWS OTel Collector to collect infrastructure metrics for your cluster, we need to [make sure all the prerequisites are satisfied.](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitorin
Will change accordingly.

2021-04-22 22:59 UTC, mxiamxia approved these changes
LGTM

2021-04-28 07:40 UTC, alolita reviewed
On hold until PRs are merged in OTEL.

2021-07-07 03:16 UTC, pingleig commented
Preview https://trusting-lewin-3415ee.netlify.app/docs/getting-started/container-insights/eks-infra

2021-07-07 16:56 UTC, mxiamxia commented on src/docs/getting-started/container-insights/eks-infra.mdx
> +curl https://raw.githubusercontent.com/aws-observability/aws-otel-collector/main/deployment-template/eks/otel-container-insight-infra.yaml |
```suggestion
curl https://raw.githubusercontent.com/aws-observability/aws-otel-collector/main/deployment-template/eks/otel-container-insights-infra.yaml |
```

2021-07-07 17:11 UTC, pxaws commented on src/docs/getting-started/container-insights/eks-infra.mdx
> +curl https://raw.githubusercontent.com/aws-observability/aws-otel-collector/main/deployment-template/eks/otel-container-insight-infra.yaml |
Thanks for catching it!

2021-07-08 06:59 UTC, alolita requested changes
Please correct all usage of:
* Container Insight Prometheus - trademark violation. please fix - see comments on related PR
* AWS OTel Collector to ADOT Collector
* collector to Collector

2021-07-08 16:17 UTC, pxaws commented
> Please correct all usage of:
> 
> * Container Insight Prometheus - trademark violation. please fix - see comments on related PR
> * AWS OTel Collector to ADOT Collector
> * collector to Collector

They are addressed in the latest commit.

2021-07-08 16:57 UTC, mxiamxia approved these changes

2021-07-08 16:58 UTC, alolita approved these changes

2021-07-08 17:00 UTC, merged