Add container insights getting start page, Prometheus and ECS Prometheus
aws-otel/aws-otel.github.io pull request #128
Opened 2021-06-24 05:03 UTC by pingleig

This PR is related to #103 and #118 as they need to move the files under `container-insights` folder and link to sub pages in the landing page `/container-insights`

- Add `/container-insights` as index for all CloudWatch Container Insights related guides
- Add `/container-insights/prometheus` for Container Insights Prometheus, common part of EKS and ECS
- Add `/container-insights/ecs-prometheus` for ECS Prometheus

2021-06-24 05:06 UTC, pingleig commented
cc @pxaws @JohnWu20 @bjrara please check the pages for container insights and container insights prometheus. We might need another page as index/common page for container insights container metrics on EKS and EC2 instance.

2021-06-24 05:32 UTC, pxaws commented on src/docs/getting-started/container-insights.mdx
> +[CloudWatch Container Insights](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/ContainerInsights.html) collect, aggregate,
I suggest we add more description to explain the infrastructure metrics and prometheus metrics like the following


[CloudWatch Container Insights](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/ContainerInsights.html) collect, aggregate, 
and summarize metrics from your containerized applications and microservices. Data are collected as as log events 
using [embedded metric format](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Embedded_Metric_Format.html). 
These log events are entries that use a structured JSON schema that enables high-cardinality data to be ingested and stored at scale. 
Amazon CloudWatch can create the aggregated CloudWatch metrics from the received EMF data. 

CloudWatch Container Insights have been supported by [CloudWatch Agent](https://github.com/aws/amazon-cloudwatch-agent) to collect both [infrastructure metrics](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/ContainerInsights.html)
and [Prometheus metrics](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/ContainerInsights-Prometheus.html). 
To migrate existing customers to use AWS Distro for OpenTelemetry, we enhance the [AWS OTel Collector](https://github.com/aws-observability/aws-otel-collector) to support the same CloudWatch Container Insights experience.

For Amazon ECS, the cluster and service level metrics are already supported ([see the public AWS doc for details](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/deploy-container-insights-ECS-adot.html))
and the support for instance level metrics is working in progress. For Amazon EKS and Kubernetes platforms on Amazon on EC2, all the infrastructure metrics are supported. 
In this tutorial, we will walk through how to enable CloudWatch Container Insights with AWS OTel Collector for an EKS EC2 cluster. 

<SectionSeparator />

## Collecting infrastructure metrics 
CloudWatch Container Insights collect metrics for many resources such as CPU, memory, disk, and network and also provide diagnostic information such as container restart failures.
The metrics are aggregated at the cluster, node, pod, task, and service level as CloudWatch metrics. To collect the infrastructure metrics, AWS OTel Collector use [AWS Container 
Insights Receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/awscontainerinsightreceiver) and [CloudWatch EMF Exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/awsemfexporter).
The following platforms are supported:
  * Amazon ECS 
  * Amazon EKS and Kubernetes platforms on Amazon EC2


## Collecting Prometheus metrics 

```
```

2021-06-24 05:35 UTC, pxaws commented on src/docs/getting-started/container-insights.mdx
> +[CloudWatch Container Insights](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/ContainerInsights.html) collect, aggregate,
The link for EKS infra metrics is `/docs/getting-started/container-insights/eks-infra`

2021-06-24 21:50 UTC, mxiamxia commented on src/docs/getting-started/container-insights.mdx
> +            <li>ECS</li>
```suggestion
        Getting Started Container Insights with ADOT
        <ul>
            <li>Setting up Container Insights on Amazon EKS</li>
            <li>Setting up Container Insights on Amazon ECS</li>
```

2021-06-24 21:52 UTC, mxiamxia commented on src/docs/getting-started/container-insights.mdx
> +            <li><Link to="/docs/getting-started/container-insights/ecs-prometheus">ECS Prometheus</Link></li>
```suggestion
        <Link to="/docs/getting-started/container-insights/prometheus">Getting Started Container Insights Prometheus Metrics with ADOT</Link>
        <ul>
            <li><Link to="/docs/getting-started/container-insights/eks-prometheus">Setting up Container Insights Prometheus on Amazon EKS</Link></li>
            <li><Link to="/docs/getting-started/container-insights/ecs-prometheus">Setting up Container Insights Prometheus on Amazon ECS</Link></li>
```

2021-06-24 21:54 UTC, mxiamxia commented on src/docs/getting-started/container-insights/ecs-prometheus.mdx
> +For using pre-built dashboard in ClouDWatch Container Insights Prometheus, you have to run a single collector for entire cluster to attach task and service metadata.
```suggestion
To use pre-built dashboard in Amazon CloudWatch Container Insights Prometheus, you have to run a single collector for entire cluster to attach task and service metadata.
```

2021-07-06 23:39 UTC, pingleig commented on src/docs/getting-started/container-insights.mdx
> +[CloudWatch Container Insights](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/ContainerInsights.html) collect, aggregate,
Done

2021-07-07 17:51 UTC, mxiamxia approved these changes
Thanks

2021-07-08 06:55 UTC, alolita reviewed
Please correct all usage of the following:
* AWS OTel Collector to ADOT Collector
* Container Insight Prometheus - this cannot be used - trademark violation ; you can use Container Insights support for Prometheus metric types
* collector to Collector

2021-07-08 07:01 UTC, alolita requested changes
Please correct all usage of the following:
* AWS OTel Collector to ADOT Collector
* Container Insight Prometheus - this cannot be used - trademark violation ; you can use Container Insights support for Prometheus metric types
* collector to Collector

2021-07-08 16:34 UTC, mxiamxia commented on src/docs/getting-started/container-insights/ecs-prometheus.mdx
> +    GettingStarted / <Link to="/docs/getting-started/container-insights">Container Insights</Link> / <Link to="/docs/getting-started/container-insights#collecting-prometheus-metrics">Container Insigh
```suggestion
    GettingStarted / <Link to="/docs/getting-started/container-insights">Container Insights</Link> / <Link to="/docs/getting-started/container-insights#collecting-prometheus-metrics">Container Insights foro Prometheus Support</Link>
```

2021-07-08 16:35 UTC, alolita approved these changes

2021-07-08 16:36 UTC, mxiamxia commented on src/docs/getting-started/container-insights/ecs-prometheus.mdx
> +Follow these steps to run the collector and Prometheus workload on ECS. You can skip some of them if you already have clusters or tasks running.
```suggestion
Follow these steps to run the ADOT Collector and Prometheus workload on ECS. You can skip some of them if you already have clusters or tasks running.
```

2021-07-08 16:36 UTC, mxiamxia commented on src/docs/getting-started/container-insights/ecs-prometheus.mdx
> +- Deploy [collector](#deploy-collector) as a replica service with 1 replica
```suggestion
- Deploy [ADOT Collector](#deploy-collector) as a replica service with 1 replica
```

2021-07-08 16:36 UTC, mxiamxia commented on src/docs/getting-started/container-insights/ecs-prometheus.mdx
> +For the collector to scrape metrics, connectivity between ECS tasks using private ip is required.
```suggestion
For the ADOT Collector to scrape metrics, connectivity between ECS tasks using private ip is required.
```

2021-07-08 16:36 UTC, mxiamxia commented on src/docs/getting-started/container-insights/ecs-prometheus.mdx
> +## Deploy Collector
```suggestion
## Deploy ADOT Collector
```

2021-07-08 16:36 UTC, mxiamxia commented on src/docs/getting-started/container-insights/ecs-prometheus.mdx
> +Collector needs to run as single instance. We use the replica service because it handles task failure.
```suggestion
ADOT Collector needs to run as single instance. We use the replica service because it handles task failure.
```

2021-07-08 16:37 UTC, mxiamxia commented on src/docs/getting-started/container-insights/ecs-prometheus.mdx
> +# Run collector as replica service on EC2
```suggestion
# Run ADOT Collector as replica service on EC2
```

2021-07-08 16:37 UTC, mxiamxia commented on src/docs/getting-started/container-insights/ecs-prometheus.mdx
> +- `logConfiguration` is for log from collector itself. Log groups for metrics/log collected by collector is configured using `AOT_CONFIG_CONTENT`.
```suggestion
- `logConfiguration` is for log from ADOT Collector itself. Log groups for metrics/log collected by collector is configured using `AOT_CONFIG_CONTENT`.
```

2021-07-08 16:37 UTC, mxiamxia commented on src/docs/getting-started/container-insights/ecs-prometheus.mdx
> +- `requiresCompatibilities` includes both EC2 and Fargate because collector is scraping metrics via HTTP and does not need special host level access.
```suggestion
- `requiresCompatibilities` includes both EC2 and Fargate because ADOT Collector is scraping metrics via HTTP and does not need special host level access.
```

2021-07-08 16:46 UTC, alolita approved these changes

2021-07-08 16:50 UTC, merged