Add Doc for ContainerInsights EKS Prometheus
aws-otel/aws-otel.github.io pull request #131
Opened 2021-07-07 01:59 UTC by bjrara

Add public doc for sContainerInsights EKS Prometheus. This doc is a part of the next release for AWS OpenTelemetry Collector.

2021-07-07 03:13 UTC, pingleig commented
Preview https://trusting-lewin-3415ee.netlify.app/docs/getting-started/container-insights/eks-prometheus

btw: @bjrara you seems forgot the screenshots for viewing dashboards ...

2021-07-07 16:54 UTC, mxiamxia approved these changes
Thanks

2021-07-07 18:51 UTC, bjrara commented
> Preview https://trusting-lewin-3415ee.netlify.app/docs/getting-started/container-insights/eks-prometheus
> 
> btw: @bjrara you seems forgot the screenshots for viewing dashboards ... and the breadcrumb for prometheus is broken because I removed the index page for prometheu, the latest should be
> 
> ```
> <p>
>     GettingStarted / <Link to="/docs/getting-started/container-insights">Container Insights</Link> / <Link to="/docs/getting-started/container-insights#collecting-prometheus-metrics">Container Insights Prometheus</Link>
> </p>
> ```

Thanks for the suggestions. Done.

2021-07-08 06:31 UTC, alolita reviewed
Fixed spelling and usage. Do not use AWS OTEL Collector. Please use ADOT Collector instead.

2021-07-08 07:02 UTC, alolita requested changes
Please correct all usage of the following:
* AWS OTel Collector to ADOT Collector
* Container Insight Prometheus - this cannot be used - trademark violation ; you can use Container Insights support for Prometheus metric types
* collector to Collector

2021-07-08 16:29 UTC, mxiamxia commented on src/docs/getting-started/container-insights/eks-prometheus.mdx
> +This section explains how to set up Prometheus monitoring with the ADOT Collector in a cluster running Amazon EKS or Kubernetes. With [default configurations](https://github.com/aws-observability/aws
```suggestion
This section explains how to set up Prometheus monitoring with the ADOT Collector in a cluster running Amazon EKS or Kubernetes. With [default configurations](https://github.com/aws-observability/aws-otel-collector/tree/main/config/eks/prometheus), the ADOT Collector automatically scrapes and imports metrics for the following workloads running in a cluster.
```

2021-07-08 16:30 UTC, mxiamxia commented on src/docs/getting-started/container-insights/eks-prometheus.mdx
> +## Deploy the AWS OTel Collector with default configuration
```suggestion
## Deploy the ADOT Collector with default configuration
```

2021-07-08 16:31 UTC, mxiamxia commented on src/docs/getting-started/container-insights/eks-prometheus.mdx
> +### Run aws-otel-collector
```suggestion
### Run ADOT Collector
```

2021-07-08 16:32 UTC, mxiamxia commented on src/docs/getting-started/container-insights/eks-prometheus.mdx
> +    GettingStarted / <Link to="/docs/getting-started/container-insights">Container Insights</Link> / <Link to="/docs/getting-started/container-insights#collecting-prometheus-metrics">Container Insigh
```suggestion
    GettingStarted / <Link to="/docs/getting-started/container-insights">Container Insights</Link> / <Link to="/docs/getting-started/container-insights#collecting-prometheus-metrics">Container Insights for Prometheus Support</Link>
```

2021-07-08 17:23 UTC, alolita approved these changes

2021-07-08 17:23 UTC, merged