Edits to fix ARNs from July 8 release
aws-otel/aws-otel.github.io pull request #133
Opened 2021-07-13 19:18 UTC by NathanielRN

# Description

Following #132 where we updated the ARNs for the July 8 release, we missed some small changes to the ARNs where the new Lambda Layers were published. This PR changes the ARNs to the correct ones.

2021-07-13 21:12 UTC, wangzlei requested changes

2021-07-13 21:12 UTC, wangzlei commented on src/docs/getting-started/lambda/lambda-java-auto-instr.mdx
> -| ap-northeast-1<br/>ap-northeast-2<br/>ap-south-1<br/>ap-southeast-1<br/>ap-southeast-2<br/>ca-central-1<br/>eu-central-1<br/>eu-north-1<br/>eu-west-1<br/>eu-west-2<br/>eu-west-3<br/>sa-east-1<br/>u
we car fix typo `aarn` by this chance

2021-07-13 21:13 UTC, NathanielRN commented on src/docs/getting-started/lambda/lambda-java-auto-instr.mdx
> -| ap-northeast-1<br/>ap-northeast-2<br/>ap-south-1<br/>ap-southeast-1<br/>ap-southeast-2<br/>ca-central-1<br/>eu-central-1<br/>eu-north-1<br/>eu-west-1<br/>eu-west-2<br/>eu-west-3<br/>sa-east-1<br/>u
Great catch!! On it!

2021-07-13 23:07 UTC, wangzlei approved these changes

2021-07-14 19:01 UTC, alolita approved these changes

2021-07-14 19:01 UTC, merged