Lambda docs
aws-otel/aws-otel.github.io pull request #142
Opened 2021-08-12 23:18 UTC by bhautikpip

Draft as awaiting merge of instrumentation SDK to OpenTelemetry Go Contributions Repo

2021-08-13 06:23 UTC, garrettwegan commented
Blocked on [contrib #983](https://github.com/open-telemetry/opentelemetry-go-contrib/pull/983) and [contrib #984](https://github.com/open-telemetry/opentelemetry-go-contrib/pull/983)

TODO: 
* Check the various links are valid once contrib PRs are merged (especially pkg.go.dev links, assume they are automatic but unsure)

2021-08-31 18:05 UTC, alolita commented
@willarmiros what is the status on this PR? are the PRs merged upstream?

2021-08-31 18:53 UTC, alolita commented
Blocked on upstream merge. Will look at later when upstream work is ready.

2021-11-16 06:46 UTC, alolita reviewed
Diagram needs to be fixed. Not viewable.

2021-11-16 13:39 UTC, bhautikpip commented
> Diagram needs to be fixed. Not viewable.

How can I validate that? Looks like we use the same image as [.NET lambda](https://github.com/aws-otel/aws-otel.github.io/search?q=img16) and .NET lambda image can be seen [here](https://aws-otel.github.io/docs/getting-started/lambda/lambda-dotnet)

2021-11-16 20:13 UTC, willarmiros requested changes
Going to need more code for the customer to copy into their `main` function, like we have in our sample app, since it's no longer a 1-line experience.

2021-11-16 20:13 UTC, willarmiros commented on src/docs/getting-started/lambda/lambda-go.mdx
> +### Code Instrumentation
We need to add a new step here to add the boilerplate code to a Lambda function. It should be step 1 to add the imports (including new ones as needed for the extra step), step 2 to copy in the code for creating and starting a TracerProvider, then step 3 is instrumenting the handler.

2021-11-16 20:13 UTC, willarmiros commented on src/docs/getting-started/lambda/lambda-go.mdx
> +### Code Instrumentation
We should also probably add a step 4 for instrumenting downstream requests too - you can just link to https://aws-otel.github.io/docs/getting-started/go-sdk/trace-manual-instr#instrumenting-an-application

2021-11-16 20:13 UTC, willarmiros commented on src/docs/getting-started/lambda/lambda-go.mdx
> +| ap-northeast-1<br/>ap-northeast-2<br/>ap-south-1<br/>ap-southeast-1<br/>ap-southeast-2<br/>ca-central-1<br/>eu-central-1<br/>eu-north-1<br/>eu-west-1<br/>eu-west-2<br/>eu-west-3<br/>sa-east-1<br/>u
```suggestion
| ap-northeast-1<br/>ap-northeast-2<br/>ap-south-1<br/>ap-southeast-1<br/>ap-southeast-2<br/>ca-central-1<br/>eu-central-1<br/>eu-north-1<br/>eu-west-1<br/>eu-west-2<br/>eu-west-3<br/>sa-east-1<br/>us-east-1<br/>us-east-2<br/>us-west-1<br/>us-west-2 | arn:aws:lambda:\<region\>:901920570463:layer:aws-otel-collector-ver-0-39-0:1 | Contains the [ADOT Collector for Lambda v0.15.0](https://github.com/aws-observability/aws-otel-collector/releases/tag/pkg%2Flambdacomponents%2Fv0.15.0)|
```

2021-11-16 22:32 UTC, willarmiros approved these changes
Just a few whitespacing issues, otherwise lgtm!

2021-11-16 22:32 UTC, willarmiros commented on src/docs/getting-started/lambda/lambda-go.mdx
> +    "go.opentelemetry.io/otel"
```suggestion
    "github.com/aws/aws-lambda-go/lambda"
    "go.opentelemetry.io/contrib/instrumentation/github.com/aws/aws-lambda-go/otellambda"
    "go.opentelemetry.io/contrib/instrumentation/github.com/aws/aws-lambda-go/otellambda/xrayconfig"
    "go.opentelemetry.io/contrib/propagators/aws/xray"
    "go.opentelemetry.io/otel"
```

2021-11-16 22:32 UTC, willarmiros commented on src/docs/getting-started/lambda/lambda-go.mdx
> +   lambda.Start(otellambda.InstrumentHandler(lambda_handler(ctx), xrayconfig.WithRecommendedOptions(tp)... ))
```suggestion
lambda.Start(otellambda.InstrumentHandler(lambda_handler(ctx), xrayconfig.WithRecommendedOptions(tp)... ))
```

2021-11-24 06:18 UTC, alolita commented
@bhautikpip @willarmiros is this PR ready to be merged?

2021-11-24 16:36 UTC, willarmiros commented
@alolita yes!

2021-11-25 00:36 UTC, NathanielRN approved these changes

2021-11-25 00:38 UTC, NathanielRN commented on src/docs/getting-started/lambda/lambda-go.mdx
> +     provides provides extension and tracing APIs you can use to instrument your Lambda function.
```suggestion
     provides extension and tracing APIs you can use to instrument your Lambda function.
```

2021-12-06 09:03 UTC, alolita approved these changes

2021-12-06 09:03 UTC, merged