added AWS X-Ray exporter data model translation behavior
aws-otel/aws-otel.github.io pull request #296
Opened 2022-04-26 19:45 UTC by bhautikpip

This PR adds AWS X-Ray exporter data model translation behavior.

2022-04-28 22:39 UTC, davikeog requested changes
Please replace {trace id example} in the trace_id row of the first table with an actual trace ID example. Also, where there are numbered lists, please put an empty line between each item in the list (right now they're collapsed). The are other cells where the line-breaks have been lost also (see the namespace row, for example). Makes it hard to read. 

I would suggest changing the 'Behavior' column to 'Notes'. This suggests that, in the absence of notes for a particular row, the behavior is self-evident, but for some rows the behavior is more subtle and needs to be described in more detail.

2022-04-30 21:13 UTC, willarmiros reviewed
Looks great! Just a couple formatting issues then good to ship :)

2022-04-30 21:13 UTC, willarmiros commented on src/docs/getting-started/x-ray.mdx
> +| Attributes                                                                    | annotations/metadata   | 1. index_all_attributes is set to false by default. By default the exporter will translate a
```suggestion
| Attributes                                                                    | annotations/metadata   | 1. index_all_attributes is set to false by default. By default the exporter will translate all the OpenTelemetry span attributes to metadata. If set to true, then it will convert all span attributes to annotations.   

2. indexed_attributes converts a list of attributes to annotations, and concerts remaining OpenTelemetry span attributes to metadata.                                                                                                                                                                                                                                             |
```

Is it possible to have these on new lines like this, or does that break the table formatting?

2022-04-30 21:13 UTC, willarmiros commented on src/docs/getting-started/x-ray.mdx
> +| SpanId                                                                        | id                     | X-Ray (sub)segment ID is a 64-bit identifier which is unique within a single trace, and cons
Did we have links to the spec for entries like these that we can add?

2022-04-30 21:13 UTC, willarmiros commented on src/docs/getting-started/x-ray.mdx
> +
```suggestion

See [AWS X-Ray Segment Documents](https://docs.aws.amazon.com/xray/latest/devguide/xray-api-segmentdocuments.html) for more information on the AWS X-Ray data model.

```

2022-05-02 18:43 UTC, bhautikpip commented on src/docs/getting-started/x-ray.mdx
> +| SpanId                                                                        | id                     | X-Ray (sub)segment ID is a 64-bit identifier which is unique within a single trace, and cons
Yeah added link to the specification like your below suggested comment for AWS X-Ray data model.

2022-05-02 18:59 UTC, bhautikpip commented
@willarmiros @davikeog addressed your comments! PTAL!

2022-05-02 19:50 UTC, willarmiros approved these changes
LGTM thanks!

2022-05-02 20:25 UTC, davikeog commented
Looks good to me at this point. Nice work!

2022-05-02 23:44 UTC, bryan-aguilar approved these changes

2022-05-02 23:44 UTC, merged