Document how to send data from the ADOT collector to Lumigo
aws-otel/aws-otel.github.io pull request #390
Opened 2022-09-14 13:54 UTC by mmanciop

Following up on my discussions with @mhausenblas and compatibility tests and relative [documentation available on the Lumigo website](https://dash.readme.com/project/lumigo/v1.1/docs/aws-distro-for-opentelemetry), this PR documents how to use ADOT with Lumigo.

2022-10-06 16:06 UTC, bryan-aguilar commented on src/docs/partners/lumigo.mdx
> +Rather, it uses the upstream `otlphttp` exporter, using the `Authorization` HTTP header with the `LumigoToken` authentication scheme to provide the Lumigo token for authentication.
```suggestion
Rather, it uses the upstream `otlphttp` exporter, using the `Authorization` HTTP header with the `LumigoToken` authentication scheme to provide the Lumigo token for authentication.
```
Can you add a link to the `otlphttp` exporter readme upstream?

2022-10-07 06:35 UTC, mmanciop commented on src/docs/partners/lumigo.mdx
> +Rather, it uses the upstream `otlphttp` exporter, using the `Authorization` HTTP header with the `LumigoToken` authentication scheme to provide the Lumigo token for authentication.
Done in 2563a5a7179476c17c178f7805c8e33d85ce1c22

2022-10-07 14:50 UTC, bryan-aguilar approved these changes

2022-10-07 14:57 UTC, mhausenblas requested changes
Thanks a lot for this, Michele! As discussed, partner strategy and onboarding is currently being worked out, will circle back ASAP here.

2024-04-19 17:10 UTC, closed without merging