Adding aws_log_groups  to the Xray Exporter config.
aws-otel/aws-otel.github.io pull request #437
Opened 2022-12-21 17:16 UTC by atshaw43

PR for functional change.
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16859/files

2022-12-28 14:48 UTC, vasireddy99 approved these changes

2022-12-28 19:08 UTC, atshaw43 commented
Thanks @vasireddy99

Can you approve the workflow? This is my first time contributing.

2022-12-28 22:16 UTC, Aneurysm9 requested changes
This needs to be held until the referenced functionality is included in a shipped version of the ADOT collector.

2022-12-28 22:35 UTC, bryan-aguilar commented on src/docs/getting-started/x-ray.mdx
> +| aws_log_groups                                                                | cloudwatch_logs        | <ul><li> The CloudWatch Log Group names. This field is given a lower priority compared to th
I don't believe this is the correct table for this. `aws_log_groups` is an additional configuration option for the exporter. Doesn't this table refer to how span attributes are translated automatically?

2022-12-29 17:29 UTC, atshaw43 commented on src/docs/getting-started/x-ray.mdx
> +| aws_log_groups                                                                | cloudwatch_logs        | <ul><li> The CloudWatch Log Group names. This field is given a lower priority compared to th
Thanks, I moved the information to another spot.

2023-01-03 19:45 UTC, atshaw43 commented on src/docs/getting-started/x-ray.mdx
> +| aws_log_groups                                                                | cloudwatch_logs        | <ul><li> The CloudWatch Log Group names. This field is given a lower priority compared to th
@bryan-aguilar 
Is there anything else I need to do to get this moving?

2023-01-04 18:26 UTC, bryan-aguilar commented on src/docs/getting-started/x-ray.mdx
> +| aws_log_groups                                                                | cloudwatch_logs        | <ul><li> The CloudWatch Log Group names. This field is given a lower priority compared to th
You can find the upstream release schedule [here](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/release.md#release-schedule). These changes should be released with upstream version `v0.69.0`. These changes will not be included in an ADOT Distribution until `v0.26.0` assuming `v0.26.0` includes upstream version `v0.69.0`. Once that version of the ADOT Collector is released then this PR can be merged. 

The ADOT Collector follows an approximately monthly release cadence and `v0.26.0` should be expected EOM January barring any unforeseen circumstances.

2023-01-23 17:27 UTC, rapphil commented on src/docs/getting-started/x-ray.mdx
> +
can we add a link to the documentation of the component?

2023-01-25 18:53 UTC, atshaw43 commented on src/docs/getting-started/x-ray.mdx
> +
Hello Raphael,

I am not following. Can you be more specific?

Are you suggesting a link to this?
https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudwatch-log-group-log-stream-naming-for-cloudtrail.html

Thanks,
Adam

2023-01-27 18:25 UTC, atshaw43 commented on src/docs/getting-started/x-ray.mdx
> +
@rapphil 
Bump

2023-01-30 05:01 UTC, rapphil commented on src/docs/getting-started/x-ray.mdx
> +
I meant the awsrayexporter.
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/awsxrayexporter

2023-01-30 22:09 UTC, atshaw43 commented on src/docs/getting-started/x-ray.mdx
> +
Done, thanks.

2023-01-31 19:34 UTC, atshaw43 commented on src/docs/getting-started/x-ray.mdx
> +
@rapphil 
Bump

2023-02-02 17:34 UTC, atshaw43 commented on src/docs/getting-started/x-ray.mdx
> +
@Aneurysm9 @rapphil @vasireddy99 
Can this be pushed out now? We have customers waiting for it.

2023-02-02 17:40 UTC, bryan-aguilar commented on src/docs/getting-started/x-ray.mdx
> +
`v0.26.0` of the ADOT Collector has not been released yet. Once that release is done these docs can be merged.

2023-02-02 20:21 UTC, vasireddy99 commented on src/docs/getting-started/x-ray.mdx
> +
Thanks for getting that to attention @atshaw43, This can be merged after release. please resolve the conflicts meanwhile.

2023-02-03 17:12 UTC, bryan-aguilar commented
@atshaw43 can you work on resolving the merge conflicts. `v0.26.0` has been released and we can move forward with this PR.

2023-02-03 17:13 UTC, bryan-aguilar approved these changes

2023-02-06 17:39 UTC, atshaw43 commented
>

2023-02-06 17:40 UTC, atshaw43 commented
> @atshaw43 can you work on resolving the merge conflicts. `v0.26.0` has been released and we can move forward with this PR.

Thanks,

I have merged the change.

2023-02-06 17:48 UTC, bryan-aguilar approved these changes

2023-02-06 17:49 UTC, merged