[parners/dynatrace] document preference for OTLP
aws-otel/aws-otel.github.io pull request #447
Opened 2023-01-10 19:33 UTC by dyladan

Dynatrace supports OTLP for both metrics and traces and recommends that method for most users. Add a section at the top of the README which documents this preference.

2023-01-12 15:15 UTC, mviitane commented on src/docs/partners/dynatrace.mdx
> +
I'd move line 20 here to explain how to export traces. Then continue with metrics.

2023-01-12 15:15 UTC, mviitane commented on src/docs/partners/dynatrace.mdx
> +Dynatrace can receive OpenTelemetry metrics in the following ways:
Could be also like this (as the user is probably thinking about how to export instead of receive):
-> OpenTelemetry metrics can be exported to Dynatrace in the following ways:

2023-01-12 15:15 UTC, mviitane commented on src/docs/partners/dynatrace.mdx
>  ## Requirements
Before showing how to configure the Dynatrace metrics exporter, we could add an example for
## Configuring the OTLP exporter to Dynatrace

We should also describe the usage of
OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE=delta

2023-01-12 15:26 UTC, mhausenblas commented
Thanks a lot for this @dyladan and much appreciated! Could you please move it to the section where the [OTLP exporter](https://aws-otel.github.io/docs/components/otlp-exporter) is described?

2023-01-12 16:17 UTC, dyladan commented on src/docs/partners/dynatrace.mdx
>  ## Requirements
I applied your other suggestions. Let's document the preference for OTLP now and we can do a rewrite where we go into more depth about OTLP configuration when I get back from my vacation on the 24th

2023-01-12 16:31 UTC, vasireddy99 commented
> 

+1

I would recommended entry in this format. 🙂

```
DynaTrace

Requirements

Configuration

Example

```

2023-01-12 16:33 UTC, dyladan commented
> > Thanks a lot for this @dyladan and much appreciated! Could you please move it to the section where the [OTLP exporter](https://aws-otel.github.io/docs/components/otlp-exporter) is described?
> 
> +1 and iI would recommend an entry in this format. 🙂
> 
> ```
> DynaTrace
> 
> Requirements
> 
> Configuration
> 
> Example
> ```

I'm working on it now

2023-01-12 16:45 UTC, mhausenblas requested changes
On hold until after sync with an ECD of W4/2023

2023-01-13 14:00 UTC, mhausenblas commented
@dyladan agreed, the way how it is structured now essentially doesn't break anything for customers, only adds on to existing material (and declaring your preference). I'll go ahead and merge it and we can decide on the deprecation timeline of the custom exporter in two weeks. Thanks!

2023-01-13 14:00 UTC, mhausenblas approved these changes

2023-01-13 14:01 UTC, merged