Add blogpost on removal of prometheusexporter from March 2023 lambda layer release
aws-otel/aws-otel.github.io pull request #501
Opened 2023-03-01 20:46 UTC by Kausik-A

Add blogpost on removal of prometheusexporter from March 2023 lambda layer release.

2023-03-01 20:54 UTC, Aneurysm9 commented on src/content/Blogs/adot-lambda-remove-prometheusexporter.mdx
> +Customers are advised to change their collector configuration to use `prometheusremotewriteexporter` by the **end of March 2023**. The instructions to set the exporter are mentioned [in our documenta
```suggestion
Customers are advised to change their collector configuration to use `prometheusremotewriteexporter` by the **end of March 2023**. The instructions to set the exporter are mentioned [in our documentation](https://aws-otel.github.io/docs/getting-started/advanced-prometheus-remote-write-configurations#prometheus-remote-write-exporter-configurations) and [upstream OpenTelemetry](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/prometheusremotewriteexporter/README.md#getting-started). If you have any questions on the migration to the new exporter, please feel free to [file an issue.](https://github.com/aws-observability/aws-otel-lambda/issues)
```

2023-03-02 19:26 UTC, mhausenblas requested changes
overall OK, pls pay attention to details

2023-03-02 19:26 UTC, mhausenblas commented on src/content/Blogs/adot-lambda-remove-prometheusexporter.mdx
> +AWS Distro for OpenTelemetry Lambda announces removal of `prometheusexporter` from March 2023 lambda layer release (v0.27.0) in favour of using `prometheusremotewriteexporter` as the default exporter
Lambda, not lambda

2023-03-02 19:26 UTC, mhausenblas commented on src/content/Blogs/adot-lambda-remove-prometheusexporter.mdx
> +AWS Distro for OpenTelemetry Lambda announces removal of `prometheusexporter` from March 2023 lambda layer release (v0.27.0) in favour of using `prometheusremotewriteexporter` as the default exporter
In US English it's favor, not favour, or?

2023-03-02 19:26 UTC, mhausenblas commented on src/content/Blogs/adot-lambda-remove-prometheusexporter.mdx
> +AWS Distro for OpenTelemetry Lambda announces removal of `prometheusexporter` from March 2023 lambda layer release (v0.27.0) in favour of using `prometheusremotewriteexporter` as the default exporter
Link PRW

2023-03-02 19:26 UTC, mhausenblas commented on src/content/Blogs/adot-lambda-remove-prometheusexporter.mdx
> +AWS Distro for OpenTelemetry Lambda announces removal of `prometheusexporter` from March 2023 lambda layer release (v0.27.0) in favour of using `prometheusremotewriteexporter` as the default exporter
Why telemetry data? It's metrics, right? So, say that.

2023-03-02 19:26 UTC, mhausenblas commented on src/content/Blogs/adot-lambda-remove-prometheusexporter.mdx
> +Customers are advised to change their collector configuration to use `prometheusremotewriteexporter` by the **end of March 2023**. The instructions to set the exporter are mentioned [in our documenta
Avoid passive voice. For example, rather than "Customers are advised" use "We advise customers" etc

2023-03-02 19:26 UTC, mhausenblas commented on src/content/Blogs/adot-lambda-remove-prometheusexporter.mdx
> +Customers are advised to change their collector configuration to use `prometheusremotewriteexporter` by the **end of March 2023**. The instructions to set the exporter are mentioned [in our documenta
in upstream OpenTelemetry

2023-03-02 19:51 UTC, Kausik-A commented on src/content/Blogs/adot-lambda-remove-prometheusexporter.mdx
> +AWS Distro for OpenTelemetry Lambda announces removal of `prometheusexporter` from March 2023 lambda layer release (v0.27.0) in favour of using `prometheusremotewriteexporter` as the default exporter
Updated.

2023-03-02 19:52 UTC, Kausik-A commented on src/content/Blogs/adot-lambda-remove-prometheusexporter.mdx
> +Customers are advised to change their collector configuration to use `prometheusremotewriteexporter` by the **end of March 2023**. The instructions to set the exporter are mentioned [in our documenta
Updated.

2023-03-02 19:56 UTC, mhausenblas approved these changes

2023-03-02 20:38 UTC, merged