Add documentation for confmap providers and Kafka receiver and exporter
aws-otel/aws-otel.github.io pull request #521
Opened 2023-03-28 23:08 UTC by rapphil

Add documentation for confmap providers and Kafka receiver and exporter.

2023-03-30 06:32 UTC, mhausenblas requested changes
Overall LGTM, thanks @rapphil! Couple of comments inline and please make sure to consistently name things, for example it should be ADOT collector (lower case) all the places.

2023-03-30 06:32 UTC, mhausenblas commented on src/docs/components/confmap-providers.mdx
> +### Yaml provider
s/Yaml/YAML

2023-03-30 06:32 UTC, mhausenblas commented on src/docs/components/confmap-providers.mdx
> +O Windows you can use the `-ConfigLocation` command line parameter of the `aws-otel-collector-ctl.ps1` control script to setup the ADOT Collector service.
s/O/On

2023-03-30 06:32 UTC, mhausenblas commented on src/docs/components/confmap-providers.mdx
> +In container environments, you can override the docker [CMD instruction](https://docs.docker.com/engine/reference/builder/#cmd) to use the configuration from the uri that you want. This can be done
s/docker/Docker

2023-03-30 06:32 UTC, mhausenblas commented on src/docs/components/confmap-providers.mdx
> +s3://example-bucket.s3.us-west-2.amazonaws.com/receivers.yaml
`s3://example-bucket.s3.us-west-2.amazonaws.com/receivers.yaml`

2023-04-05 04:15 UTC, rapphil commented on src/docs/components/kafka-receiver-exporter.mdx
> +For a Kafka receiver the configuration would look like:
I added an real example of the components in action. There is no much use of consuming from the topics directly because the components operate mainly on OTLP protocol.

2023-04-06 23:35 UTC, rapphil commented
Please do not release. @bryan-aguilar should be the one releasing this.

2023-04-07 19:31 UTC, merged