Update python & java auto-instrumentation doc.
aws-otel/aws-otel.github.io pull request #711
Opened 2024-04-22 16:57 UTC by zzhlogin

*Issue #, if available:*

*Description of changes:*
Update python & java auto-instrumentation doc:
1. Java auto-instrumentation doc:  Add CloudWatch Application Signals section.
2. Python auto-instrumentation doc: Update to use AWS distro instead of using distro from upstream for auto-instrumentation.

The doc have been review by team and product manager.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-04-22 19:42 UTC, vasireddy99 commented on src/docs/getting-started/python-sdk/auto-instr.mdx
> -#### Creating Metrics
does the aws-opentelemetry-distro package support only traces ? if not, can this example and rest of the relevant documentation stay.

2024-04-22 20:27 UTC, zzhlogin commented on src/docs/getting-started/python-sdk/auto-instr.mdx
> -#### Creating Metrics
`aws-opentelemetry-distro` package support trace, metrics and logs. We use this package to auto-instrument python applications. To my understanding, we should configure our auto-instrumentation by only setting up environment variables instead of directly modifying the code. 

For this `Creating Metrics` section, it seems more likely belongs to manual instrumentation, I'm actually don't understand why did we put it here under auto-instrumentation page. 

I checked python manual instrumentation page, it have much more details in how to configuring meter, trace, metrics: https://aws-otel.github.io/docs/getting-started/python-sdk/manual-instr#sending-traces-and-metrics. We already cover it there. So, I'm removing this section.

2024-04-23 06:39 UTC, mhausenblas requested changes
Overall, LGTM, thanks! Only some minor nits inline.

2024-04-23 06:39 UTC, mhausenblas commented on src/docs/getting-started/java-sdk/auto-instr.mdx
> +You can use CloudWatch Application Signals to automatically instrument your applications on AWS using ADOT java auto-instrumentation so that you can monitor current application health and track long-
s/java/Java

2024-04-23 06:39 UTC, mhausenblas commented on src/docs/getting-started/python-sdk/auto-instr.mdx
> +OpenTelemetry Python supports automatic instrumentation. It automatically produces spans with telemetry data describing the values used by the python frameworks in your application without adding a s
s/python/Python
s/X-Ray/AWS X-Ray

2024-04-23 06:39 UTC, mhausenblas commented on src/docs/getting-started/python-sdk/auto-instr.mdx
> +The ADOT Python Auto-Instrumentation can be configured to use X-Ray remote sampling by setting the environment variable `OTEL_TRACES_SAMPLER=xray`. You will also need to configure the OpenTelemetry c
s/Auto-Instrumentation/auto-instrumentation

2024-04-23 16:31 UTC, zzhlogin commented on src/docs/getting-started/python-sdk/auto-instr.mdx
> +OpenTelemetry Python supports automatic instrumentation. It automatically produces spans with telemetry data describing the values used by the python frameworks in your application without adding a s
Updated

2024-04-23 16:32 UTC, zzhlogin commented on src/docs/getting-started/python-sdk/auto-instr.mdx
> +The ADOT Python Auto-Instrumentation can be configured to use X-Ray remote sampling by setting the environment variable `OTEL_TRACES_SAMPLER=xray`. You will also need to configure the OpenTelemetry c
Updated

2024-04-23 16:40 UTC, mhausenblas approved these changes
LGTM

2024-04-23 16:42 UTC, merged